[package]
name = "flappy_dragon"
version = "0.1.0"
edition = "2021"


[workspace]
members  = [ "flappy_dragon_base", "my_library" ]

[workspace.dependencies]
bevy = "0.12"
anyhow = "1"
rand = "0.8"
rand_pcg = { version = "0.3" }
rand_xorshift = { version = "0.3" }
